[aliases]
bob='age1xgrjk6eyckfkj85zac7jzhwusagj0vh77y64pk0tpczs5qgjmvdswgmjyq'

[config]
"protected/secrets2bobs.md" = ['bob']
"protected" = ['bob']
"**/*.md" = ['bob']
"plain/*.not" = ["age1xgrjk6eyckfkj85zac7jzhwusagj0vh77y64pk0tpczs5qgjmvdswgmjyq"]
